### ISSUE TITLE
thread 'main' panicked at 'Failed to read non-consensus contract metadata, even though contract exists in MARF.'

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarity-repl#11]
Latest REPL crashes with any input. This is on M1, v0.9.0 worked okay.

```
marvin@Leviathan ~ % clarity-repl
clarity-repl v0.11.0
Enter "::help" for usage hints.
Connected to a transient in-memory database.

>> (+ 1 2)
thread 'main' panicked at 'Failed to read non-consensus contract metadata, even though contract exists in MARF.', /Users/marvin/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.11.0/src/clarity/database/clarity_db.rs:325:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MarvinJanssen** [comment]
I guess this is solved.

**Comment by pors** [comment]
I have the same issue (on M1 hardware):

```
➜ clarity-repl
clarity-repl v0.16.0
Enter "::help" for usage hints.
Connected to a transient in-memory database.

>> (+ 3 4)
thread 'main' panicked at 'Failed to read non-consensus contract metadata, even though contract exists in MARF.', /Users/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.16.0/src/clarity/database/clarity_db.rs:328:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pors** [comment]
Am I the only one with this problem? I installed clarity-repl from scratch (0.17.0) this time, and the problem persists.

**Comment by MatthewTang** [comment]
I am encountering the same issue on m1 macbook pro

clarity-repl v0.17.0

i'm running terminal with Rosetta 
the issue still persists

**Comment by MatthewTang** [comment]
@MarvinJanssen , how did you solve it ? thanks a lot

**Comment by pors** [comment]
@MatthewTang I didn't solve it, but now use `clarinet console`.

**Comment by pors** [comment]
@lgalabru  I think this issue should be reopened?

I read in the Stacks Discord that someone had the same issue on an Intel Mac.

Backtrace:

```
➜ export RUST_BACKTRACE=full; clarity-repl
clarity-repl v0.17.0
Enter "::help" for usage hints.
Connected to a transient in-memory database.

>>
thread 'main' panicked at 'Failed to read non-consensus contract metadata, even though contract exists in MARF.', /Users/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.17.0/src/clarity/database/clarity_db.rs:328:68
stack backtrace:
   0:        0x100b53348 - std::backtrace_rs::backtrace::libunwind::trace::h3788418f13e49f6e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x100b53348 - std::backtrace_rs::backtrace::trace_unsynchronized::hf189cd7ee07b4d2b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100b53348 - std::sys_common::backtrace::_print_fmt::hcd10aea219dfc188
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x100b53348 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha9fb0042c142196e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x100b6cff4 - core::fmt::write::ha61991bf8ecf136a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:        0x100b4dcd4 - std::io::Write::write_fmt::h46c2e7b09a3411d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:        0x100b54c34 - std::sys_common::backtrace::_print::h66fb61bcb7af7f3c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x100b54c34 - std::sys_common::backtrace::print::hd77bcd12ac793f65
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x100b54c34 - std::panicking::default_hook::{{closure}}::h2e75467530bdcca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:        0x100b54800 - std::panicking::default_hook::habe288fd56f5750a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:        0x100b55274 - std::panicking::rust_panic_with_hook::h0de8caef2b5cd059
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:        0x100b54dc0 - std::panicking::begin_panic_handler::{{closure}}::hacf45a4761576516
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:        0x100b53820 - std::sys_common::backtrace::__rust_end_short_backtrace::hc8935facac9e6044
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x100b54d28 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:        0x100b87800 - core::panicking::panic_fmt::h976396c8435074ae
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:        0x100b8774c - core::option::expect_failed::h22dd835cf251967d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:1615:5
  16:        0x10088a0b0 - clarity_repl::clarity::database::clarity_db::ClarityDatabase::get_contract::h70740961642111d6
  17:        0x1009407f4 - clarity_repl::clarity::costs::LimitedCostTracker::new::h35e5917490e5757a
  18:        0x100961fb0 - clarity_repl::repl::interpreter::ClarityInterpreter::execute::hecb0fb591271e9da
  19:        0x10096167c - clarity_repl::repl::interpreter::ClarityInterpreter::run::h071f28376dd20946
  20:        0x100936308 - clarity_repl::repl::session::Session::interpret::h558eacd9b482b38d
  21:        0x1009349f8 - clarity_repl::repl::session::Session::formatted_interpretation::h0fa826d2e694064b
  22:        0x100932978 - clarity_repl::repl::session::Session::handle_command::ha3c9cdbb8ebc1276
  23:        0x10094b304 - clarity_repl::frontend::terminal::Terminal::start::h8ce0acabd9d34468
  24:        0x10097ac64 - clarity_repl::main::hea9230f60179dc0d
  25:        0x1008ca71c - std::sys_common::backtrace::__rust_begin_short_backtrace::hd199906047741ec4
  26:        0x10096684c - std::rt::lang_start::{{closure}}::h06afa0ac174dee9e
  27:        0x100b556ec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h51c1d4e6d77bdcbb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  28:        0x100b556ec - std::panicking::try::do_call::h89fe052533bafbda
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  29:        0x100b556ec - std::panicking::try::h46d7f0e49ad79887
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  30:        0x100b556ec - std::panic::catch_unwind::h39132fca9d95ef81
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  31:        0x100b556ec - std::rt::lang_start_internal::{{closure}}::h6539b3c59dc74c9d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  32:        0x100b556ec - std::panicking::try::do_call::h5b104bf56577bb16
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  33:        0x100b556ec - std::panicking::try::h7769cac6f81ef323
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  34:        0x100b556ec - std::panic::catch_unwind::h3b24c77fb952102f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  35:        0x100b556ec - std::rt::lang_start_internal::hb4d1fe995f6e94ee
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  36:        0x10097c6b0 - _main

```

**Comment by pors** [comment]
Building from source does work @MatthewTang

**Comment by alacret** [comment]
Have this same problem using M1 chip and clarity-repl v0.28.0

**Comment by Oyeins-GUI** [comment]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidTypeDescription', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\clarity-repl-0.27.0\src\analysis\ast_dependency_detector.rs:497:82
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When I run the "clarinet check" command on the terminal I had this error above. How can I fix it?
